# Sleep settings
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=3600000

# Enable ZMK Studio
CONFIG_ZMK_STUDIO=y

#Enable Encoder support
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

CONFIG_MINIMAL_LIBC=y
